// Emit a TypeScript schema file from a flat list of CatalogColumns.
//
// Pure: takes data, returns a string. The output imports
// `defineTable` and `columnType` from the package's schema-runtime
// entry point and emits one `defineTable(...)` per table. Database
// case is preserved; nothing is renamed.
//
// Out of scope: catalog reading (src/introspect/readCatalog.ts);
// type mapping (src/introspect/mapTypes.ts); file I/O (src/introspect/bin.ts).

import { mapPostgresType } from "./mapTypes.js";
import type { CatalogColumn } from "./readCatalog.js";

const HEADER = `// This file is generated by tenon-generate. Do not edit by hand.
// Re-run \`tenon-generate\` after schema migrations.

import { columnType, defineTable } from "@notahat/tenon/schema-runtime";
`;

/** Group columns by (schema, table) preserving catalog order. */
function groupByTable(
  columns: readonly CatalogColumn[],
): Map<string, CatalogColumn[]> {
  const groups = new Map<string, CatalogColumn[]>();
  for (const column of columns) {
    const key = `${column.schema}.${column.tableName}`;
    const existing = groups.get(key);
    if (existing === undefined) {
      groups.set(key, [column]);
    } else {
      existing.push(column);
    }
  }
  return groups;
}

/**
 * Build a JS-safe identifier from a (possibly snake_case or unusual)
 * table name. Non-identifier characters are replaced with underscores
 * and a leading digit is prefixed with `_`.
 */
function toExportName(tableName: string): string {
  const sanitised = tableName.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(sanitised) ? `_${sanitised}` : sanitised;
}

/** Render a TypeScript string literal, escaping `"` and `\`. */
function renderStringLiteral(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** Render a single column line inside a defineTable call. */
function renderColumnLine(column: CatalogColumn): string {
  const mapped = mapPostgresType(column.typname);
  const fallbackComment = mapped.isFallback
    ? ` // unknown Postgres type "${column.typname}"; falling back to string`
    : "";
  const key = renderStringLiteral(column.columnName);
  const sqlTag = renderStringLiteral(mapped.sqlTag);
  const flags =
    `nullable: ${column.nullable}, ` +
    `hasDefault: ${column.hasDefault}, ` +
    `isGenerated: ${column.isGenerated}`;
  return (
    `  ${key}: columnType<${mapped.tsType}, ${sqlTag}>(` +
    `{ ${flags} }),${fallbackComment}`
  );
}

/** Render a defineTable(...) block for one table. */
function renderTable(
  schema: string,
  tableName: string,
  columns: readonly CatalogColumn[],
): string {
  const exportName = toExportName(tableName);
  const lines = [
    `export const ${exportName} = defineTable(` +
      `${renderStringLiteral(schema)}, ${renderStringLiteral(tableName)}, {`,
    ...columns.map(renderColumnLine),
    "});",
  ];
  return lines.join("\n");
}

/**
 * Emit a fully-formed TypeScript module string for the given catalog
 * columns. The caller is responsible for writing the string to disk.
 */
export function emitSchemaFile(columns: readonly CatalogColumn[]): string {
  const groups = groupByTable(columns);
  const blocks: string[] = [];
  for (const [, tableColumns] of groups) {
    const first = tableColumns[0];
    if (first === undefined) continue;
    blocks.push(renderTable(first.schema, first.tableName, tableColumns));
  }
  return `${HEADER}\n${blocks.join("\n\n")}\n`;
}
