// Emit a TypeScript schema file from a flat list of CatalogColumns,
// CatalogForeignKeys, and CatalogPrimaryKeys.
//
// Pure: takes data, returns a string. The output imports
// `defineTable` and `columnType` from the package's schema-runtime
// entry point and emits one `defineTable(...)` per table. Database
// case is preserved; nothing is renamed. Single-column foreign keys
// are rendered as a fourth argument to `defineTable`; composite FKs
// are dropped at emit time with a generated comment because the
// type-level inference surface in v1 only handles single-column FKs.
// Primary keys are rendered as a fifth argument (the empty PK is
// omitted to keep the common no-PK case concise).
//
// Out of scope: catalog reading (src/introspect/readCatalog.ts);
// type mapping (src/introspect/mapTypes.ts); file I/O (src/introspect/bin.ts).

import { mapPostgresType } from "./mapTypes.js";
import type {
  CatalogColumn,
  CatalogForeignKey,
  CatalogPrimaryKey,
} from "./readCatalog.js";

const HEADER = `// This file is generated by tenon-generate. Do not edit by hand.
// Re-run \`tenon-generate\` after schema migrations.

import { columnType, defineTable } from "@notahat/tenon/schema-runtime";
`;

/** Group items by a string key, preserving input order within each group. */
function groupBy<Item>(
  items: readonly Item[],
  keyOf: (item: Item) => string,
): Map<string, Item[]> {
  const groups = new Map<string, Item[]>();
  for (const item of items) {
    const key = keyOf(item);
    const existing = groups.get(key);
    if (existing === undefined) {
      groups.set(key, [item]);
    } else {
      existing.push(item);
    }
  }
  return groups;
}

/** Key shared by CatalogColumn and CatalogForeignKey for table grouping. */
function tableKey(item: { schema: string; tableName: string }): string {
  return `${item.schema}.${item.tableName}`;
}

/**
 * Build a JS-safe identifier from a (possibly snake_case or unusual)
 * table name. Non-identifier characters are replaced with underscores
 * and a leading digit is prefixed with `_`.
 */
function toExportName(tableName: string): string {
  const sanitised = tableName.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(sanitised) ? `_${sanitised}` : sanitised;
}

/** Render a TypeScript string literal, escaping `"` and `\`. */
function renderStringLiteral(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** Render a single column line inside a defineTable call. */
function renderColumnLine(column: CatalogColumn): string {
  const mapped = mapPostgresType(column.typname);
  const fallbackComment = mapped.isFallback
    ? ` // unknown Postgres type "${column.typname}"; falling back to string`
    : "";
  const key = renderStringLiteral(column.columnName);
  const sqlTag = renderStringLiteral(mapped.sqlTag);
  const flags =
    `nullable: ${column.nullable}, ` +
    `hasDefault: ${column.hasDefault}, ` +
    `isGenerated: ${column.isGenerated}`;
  return (
    `  ${key}: columnType<${mapped.tsType}, ${sqlTag}>(` +
    `{ ${flags} }),${fallbackComment}`
  );
}

/** Render a string-literal array, e.g. ["a", "b"]. */
function renderStringArray(values: readonly string[]): string {
  return `[${values.map(renderStringLiteral).join(", ")}]`;
}

/** Render one FK as an indented object literal block. */
function renderForeignKeyEntry(fk: CatalogForeignKey): string {
  return [
    "  {",
    `    name: ${renderStringLiteral(fk.name)},`,
    `    columns: ${renderStringArray(fk.columns)},`,
    `    referencedSchema: ${renderStringLiteral(fk.referencedSchema)},`,
    `    referencedTable: ${renderStringLiteral(fk.referencedTable)},`,
    `    referencedColumns: ${renderStringArray(fk.referencedColumns)},`,
    "  },",
  ].join("\n");
}

/** A two-line comment explaining why a composite FK was dropped. */
function renderSkippedCompositeComment(fk: CatalogForeignKey): string {
  const onCols = fk.columns.join(", ");
  const refTable = `${fk.referencedSchema}.${fk.referencedTable}`;
  return [
    `// Skipped composite foreign key ${renderStringLiteral(fk.name)} ` +
      `on (${onCols}) referencing ${refTable}:`,
    `// composite FKs are not yet surfaced in tenon's type-level inference.`,
  ].join("\n");
}

/** Render the trailing `, primaryKey` argument to `defineTable`, if any. */
function renderPrimaryKey(pk: CatalogPrimaryKey | undefined): string | null {
  if (pk === undefined || pk.columns.length === 0) return null;
  return `{ columns: ${renderStringArray(pk.columns)} }`;
}

/**
 * Render a defineTable(...) block for one table, plus any preamble
 * comments documenting FKs we chose not to emit.
 */
function renderTable(
  schema: string,
  tableName: string,
  columns: readonly CatalogColumn[],
  foreignKeys: readonly CatalogForeignKey[],
  primaryKey: CatalogPrimaryKey | undefined,
): string {
  const exportName = toExportName(tableName);
  const singleColumnFks = foreignKeys.filter((fk) => fk.columns.length === 1);
  const compositeFks = foreignKeys.filter((fk) => fk.columns.length > 1);
  const pkLiteral = renderPrimaryKey(primaryKey);

  const preamble = compositeFks.map(renderSkippedCompositeComment);
  const header =
    `export const ${exportName} = defineTable(` +
    `${renderStringLiteral(schema)}, ${renderStringLiteral(tableName)}, {`;

  const columnLines = columns.map(renderColumnLine);

  // Four cases by what's present after the columns object: nothing,
  // FKs only, PK only (FKs slot is `[]`), or both. Keeping the common
  // no-FK / no-PK case concise is worth the small branching.
  if (singleColumnFks.length === 0 && pkLiteral === null) {
    return [...preamble, header, ...columnLines, "});"].join("\n");
  }
  if (singleColumnFks.length === 0) {
    return [
      ...preamble,
      header,
      ...columnLines,
      `}, [], ${pkLiteral});`,
    ].join("\n");
  }
  if (pkLiteral === null) {
    return [
      ...preamble,
      header,
      ...columnLines,
      "}, [",
      ...singleColumnFks.map(renderForeignKeyEntry),
      "]);",
    ].join("\n");
  }
  return [
    ...preamble,
    header,
    ...columnLines,
    "}, [",
    ...singleColumnFks.map(renderForeignKeyEntry),
    `], ${pkLiteral});`,
  ].join("\n");
}

/**
 * Emit a fully-formed TypeScript module string for the given catalog
 * data. Foreign keys and primary keys default to empty lists to keep
 * the call sites concise when only columns are being emitted.
 */
export function emitSchemaFile(
  columns: readonly CatalogColumn[],
  foreignKeys: readonly CatalogForeignKey[] = [],
  primaryKeys: readonly CatalogPrimaryKey[] = [],
): string {
  const columnGroups = groupBy(columns, tableKey);
  const foreignKeyGroups = groupBy(foreignKeys, tableKey);
  const primaryKeyByTable = new Map(
    primaryKeys.map((pk) => [tableKey(pk), pk]),
  );
  const blocks: string[] = [];
  for (const [, tableColumns] of columnGroups) {
    const first = tableColumns[0];
    if (first === undefined) continue;
    const key = tableKey(first);
    const fksForTable = foreignKeyGroups.get(key) ?? [];
    const pkForTable = primaryKeyByTable.get(key);
    blocks.push(
      renderTable(
        first.schema,
        first.tableName,
        tableColumns,
        fksForTable,
        pkForTable,
      ),
    );
  }
  return `${HEADER}\n${blocks.join("\n\n")}\n`;
}
